name: shelf_dav
description: >-
  A WebDAV server implementation for Dart using the Shelf web framework.
version: 1.0.0
homepage: https://github.com/libdbm/shelf-dav
repository: https://github.com/libdbm/shelf-dav
issue_tracker: https://github.com/libdbm/shelf-dav/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  file: ^7.0.0
  path: ^1.9.0
  mime_type: ^1.0.0
  xml: ^6.5.0
  logging: ^1.2.0
  crypto: ^3.0.3
  synchronized: ^3.1.0
  libdbm: ^0.2.0

dev_dependencies:
  http: ^1.2.1
  lints: ^6.0.0
  test: ^1.25.2
  test_process: ^2.1.0
  webdav_client: ^1.2.1
  shelf_static: any
